/**
 * Gemini CLI Adapter
 * Gemini 使用 GEMINI.md 单文件格式
 */

const fs = require('fs');
const path = require('path');
const AdapterInterface = require('../common/interface');
const { fileExists, mergeMarkdownFiles, getProjectRoot } = require('../common/utils');

class GeminiAdapter extends AdapterInterface {
  constructor() {
    super();
    this.pluginPath = null;
  }

  /**
   * 平台名称
   */
  getPlatformName() {
    return 'gemini';
  }

  /**
   * 检测当前环境是否为 Gemini CLI
   */
  detect() {
    const root = getProjectRoot();
    // Gemini CLI 特征：GEMINI.md 存在
    return fileExists(path.join(root, 'GEMINI.md'));
  }

  /**
   * 注册 skill
   * Gemini 通过 GEMINI.md 内嵌 skill 定义
   */
  registerSkill(skillName, skillConfig) {
    // 更新 GEMINI.md 添加 skill
    this._updateGeminiMd(skillName, skillConfig);
    return true;
  }

  /**
   * 触发 skill
   * Gemini 通过 prompt 引导触发
   */
  async triggerSkill(skillName, context) {
    const skillPath = path.join(this.pluginPath, 'skills', skillName, 'SKILL.md');

    if (!fs.existsSync(skillPath)) {
      throw new Error(`Skill ${skillName} not found`);
    }

    const skillContent = fs.readFileSync(skillPath, 'utf8');

    return {
      platform: 'gemini',
      skillName: skillName,
      skillContent: skillContent,
      context: context,
      triggerMethod: 'prompt',
      instructions: `Include skill instructions in your prompt: "Use project-doc ${skillName} skill"`
    };
  }

  /**
   * 加载规则文件
   * Gemini 从 GEMINI.md 中读取规则
   */
  loadRule(rulePath) {
    // Gemini 规则已合并到 GEMINI.md
    const geminiMdPath = path.join(getProjectRoot(), 'GEMINI.md');

    if (!fs.existsSync(geminiMdPath)) {
      throw new Error('GEMINI.md not found');
    }

    const content = fs.readFileSync(geminiMdPath, 'utf8');

    // 提取对应规则部分
    const ruleName = path.basename(rulePath, '.md');
    const ruleMatch = content.match(new RegExp(`## ${ruleName}[\\s\\S]*?(?=## |$)`));

    if (ruleMatch) {
      return ruleMatch[0];
    }

    return content;
  }

  /**
   * 获取上下文
   */
  getContext() {
    return {
      projectPath: getProjectRoot(),
      pluginPath: this.pluginPath,
      platform: 'gemini',
      cwd: process.cwd()
    };
  }

  /**
   * 初始化插件
   * 生成 GEMINI.md 文件
   */
  initialize(pluginPath) {
    this.pluginPath = pluginPath;

    // 读取所有 rules 和 skills
    const rulesDir = path.join(pluginPath, 'rules');
    const skillsDir = path.join(pluginPath, 'skills');

    // 生成 GEMINI.md
    this._generateGeminiMd(rulesDir, skillsDir);

    return true;
  }

  /**
   * 生成 GEMINI.md
   * @private
   */
  _generateGeminiMd(rulesDir, skillsDir) {
    const outputPath = path.join(getProjectRoot(), 'GEMINI.md');

    // 头部
    let content = `# Project-Doc for Gemini CLI

> This file integrates project-doc with Gemini CLI.
> Include relevant sections in your prompts.

---

## Overview

Project-Doc 是专为 AI 编程助手打造的项目治理专家。

**核心能力**：
- 文档自动化治理
- 任务状态追踪
- 需求变更追溯

---

`;

    // 合并 rules
    content += `## Rules\n\n`;

    if (fs.existsSync(rulesDir)) {
      const rulesFiles = fs.readdirSync(rulesDir)
        .filter(f => f.endsWith('.md'));

      rulesFiles.forEach(file => {
        const ruleContent = fs.readFileSync(path.join(rulesDir, file), 'utf8');
        content += `### ${file}\n\n${ruleContent}\n\n---\n\n`;
      });
    }

    // 合并 skills
    content += `## Skills\n\n`;

    if (fs.existsSync(skillsDir)) {
      const skillDirs = fs.readdirSync(skillsDir, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name);

      skillDirs.forEach(skillName => {
        const skillPath = path.join(skillsDir, skillName, 'SKILL.md');
        if (fs.existsSync(skillPath)) {
          const skillContent = fs.readFileSync(skillPath, 'utf8');
          content += `### ${skillName}\n\n${skillContent}\n\n---\n\n`;
        }
      });
    }

    // 使用说明
    content += `## Usage

在 Gemini CLI prompt 中引用相关部分：

\`\`\`
Use project-doc project-init skill to initialize documentation structure.
\`\`\`

---

Generated by project-doc v1.0.0
`;

    fs.writeFileSync(outputPath, content);
  }

  /**
   * 更新 GEMINI.md 添加 skill
   * @private
   */
  _updateGeminiMd(skillName, skillConfig) {
    const outputPath = path.join(getProjectRoot(), 'GEMINI.md');
    const skillPath = path.join(this.pluginPath, 'skills', skillName, 'SKILL.md');

    if (!fs.existsSync(skillPath)) {
      return;
    }

    const skillContent = fs.readFileSync(skillPath, 'utf8');
    const newSection = `### ${skillName}\n\n${skillContent}\n\n---\n\n`;

    let existingContent = '';
    if (fs.existsSync(outputPath)) {
      existingContent = fs.readFileSync(outputPath, 'utf8');
    }

    // 在 Skills 部分添加
    const skillsMatch = existingContent.match(/## Skills\n\n/);
    if (skillsMatch) {
      const insertPos = skillsMatch.index + skillsMatch[0].length;
      const updatedContent = existingContent.slice(0, insertPos) +
                            newSection +
                            existingContent.slice(insertPos);
      fs.writeFileSync(outputPath, updatedContent);
    } else {
      // 添加新的 Skills 部分
      fs.writeFileSync(outputPath, existingContent + `## Skills\n\n${newSection}`);
    }
  }
}

module.exports = GeminiAdapter;